FROM node:18

WORKDIR /src

COPY package*.json ./

# Install the dependencies
RUN npm install

COPY . .

# Build the application 
RUN npm run build

EXPOSE 8081

# Command to run the 
CMD [ "npm", "run", "start"]