services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db

  talando:
    build:
      context: ./build
      dockerfile: DockerFile
    ports:
      - "8081:8081"
    restart: "always"
    environment:
      - NODE_ENV=development
volumes:
  mongo-data:
